apiVersion: v1
kind: Secret
metadata:
  name: office365-secrets
  namespace: office365
type: Opaque
stringData:
    APP_NAME="Office365 Reports"
    ENVIRONMENT="development"
    LOG_LEVEL="INFO"
    STORAGE_PROVIDER="local"
    DB_HOST="localhost"
    DB_PORT="3306"
    DB_NAME="office365_reports"
    DB_USER="appuser"
    DB_PASSWORD="app123"
    SECRET_KEY="S9URY9vYJKtpEJUECaqgjUeRsleYF7Knng6FN0J3keY="
    SMTP_HOST="email-smtp.sa-east-1.amazonaws.com"
    SMTP_PORT="587"
    SMTP_USER="AKIAS3GYAJV3KTQAA72N"
    SMTP_PASSWORD="BG2mt43f1AbttEaKo0RA6EzO3L57mo+vDx3gpf0LXxFb"
    SMTP_SENDER_NAME="Blocktime Relatórios Office365"
    SMTP_USE_TLS="true"
    SMTP_SENDER_EMAIL="clouteam@blocktime.com.br"
    SMTP_SEND_ENABLED="false"
    MAESTRO_ENABLED="false"
    MAESTRO_MFA_URL="https://ue2pct2dnqdukbie6pcbshugcq0pkxcf.lambda-url.us-east-1.on.aws/"
    MAESTRO_MFA_TOKEN=blocktime.577818.JRgmcxHv1zGXfKBlrbHx77OopR5Yja5ZdVm2QbTqWiSJLkvjEI0C2cAUlLeK4ytw"
    MAESTRO_LICENCA_URL="https://ue2pct2dnqdukbie6pcbshugcq0pkxcf.lambda-url.us-east-1.on.aws/
    MAESTRO_LICENCA_TOKEN="blocktime.578461.N2GjgByzsYiRbiLO05x8LDzUroKIb8RfnUqaF0AID4dfuPeSaXHr3lFYwhXMC7G5"
    MAESTRO_ADMIN_EMAIL="cloudteam@blocktime.com.br"
