"""add_recipient_fields_to_customers

Revision ID: 455413fadd7b
Revises: e23b4fff1264
Create Date: 2026-06-03 14:02:08.802345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '455413fadd7b'
down_revision: Union[str, Sequence[str], None] = 'e23b4fff1264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('recipient_email', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('recipient_name', sa.String(length=255), nullable=True))
    op.alter_column('customers', 'client_secret',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Valor criptografado com Fernet — nunca armazenado em texto claro',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'client_secret',
               existing_type=mysql.TEXT(),
               comment='Valor criptografado com Fernet — nunca armazenado em texto claro',
               existing_nullable=False)
    op.drop_column('customers', 'recipient_name')
    op.drop_column('customers', 'recipient_email')
    # ### end Alembic commands ###
