"""add_razao_social_cnpj_to_customers

Revision ID: 63e18650d143
Revises: 455413fadd7b
Create Date: 2026-06-08 11:18:46.317569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '63e18650d143'
down_revision: Union[str, Sequence[str], None] = '455413fadd7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.add_column('customers', sa.Column('razao_social', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('cnpj', mysql.CHAR(length=18), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'cnpj')
    op.drop_column('customers', 'razao_social')
    # ### end Alembic commands ###
