"""add_sharepoint_cert_fields

Revision ID: a1b2c3d4e5f6
Revises: 63e18650d143
Create Date: 2026-06-29 09:00:00.000000

Adiciona as colunas usadas pela integração de autenticação app-only no
SharePoint (certificado X.509 cifrado + nome do tenant SharePoint).

Todas as colunas são nullable: clientes já cadastrados continuam
funcionando sem certificado até que um seja gerado para eles
(via `cli cert-generate <id>` ou na próxima renovação).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '63e18650d143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Nome do tenant no SharePoint (ex: 'duco' → duco.sharepoint.com)
    op.add_column('customers', sa.Column('sharepoint_name', sa.String(length=128), nullable=True))

    # Certificado para autenticação app-only no SharePoint.
    # O .pfx é guardado cifrado (Fernet, base64) — mesma camada que protege
    # o client_secret. As demais colunas são metadados usados na
    # autenticação (thumbprint/x5t) e no fluxo de renovação (not_after).
    op.add_column('customers', sa.Column('cert_pfx', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('cert_thumbprint', sa.String(length=64), nullable=True))
    op.add_column('customers', sa.Column('cert_x5t', sa.String(length=64), nullable=True))
    op.add_column('customers', sa.Column('cert_not_after', sa.DateTime(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'cert_not_after')
    op.drop_column('customers', 'cert_x5t')
    op.drop_column('customers', 'cert_thumbprint')
    op.drop_column('customers', 'cert_pfx')
    op.drop_column('customers', 'sharepoint_name')
    # ### end Alembic commands ###